packages:
  - apps/server
  - apps/web
  - packages/*
  - infra/budmonctl
  - tools/*
peerDependencyRules:
  allowedVersions:
    "eslint-plugin-jsx-a11y>eslint": "10"
ignoredBuiltDependencies:
  - esbuild
